### ISSUE TITLE
Random Exception in server tick loop crash with latest 1.7.10 version

### ISSUE THREAD

**Issue by comus777** [TheCBProject/ChickenChunks#12]
I was in the middle of playing my game when suddenly I get this crash for no reason
[crash-2017-03-21_03.05.11-server.txt](https://github.com/TheCBProject/ChickenChunks/files/856065/crash-2017-03-21_03.05.11-server.txt)

It seems to have appeared completely out of nowhere, and occurs every time I boot up the world.

**Comment by covers1624** [comment]
1.7 is no longer supported sorry.
