### ISSUE TITLE
[1.10.2]Crash, Can't find provider for dim-28

### ISSUE THREAD

**Issue by Pyrom4nia** [TheCBProject/ChickenChunks#13]
Chickenchunks will crash the game when Galacticraft is installed
Galacticraft Build 77
Chickenchunks Version 2.2.0.52
https://pastebin.com/8yNPrJZE

**Comment by covers1624** [comment]
The old cleanChunks mechanic has been removed in 1,11. Pending release. fixing more stuffs.
