### ISSUE TITLE
Crash on start server, Sponge 1.10

### ISSUE THREAD

**Issue by mkrtes** [TheCBProject/ChickenChunks#16]
Crashlog https://pastebin.com/hJXUBefN

**Comment by EmanYm** [comment]
My experience is that the chunk loader has issues on Sponge.
Also.  Are you absolutely positive that everything you are using is compatible with SpongeForge, and has no conflicts with anything else you're using?

**Comment by mkrtes** [comment]
@EmanYm Sure. As soon as I remove this mod everything is working. Maybe it's a problem Sponge. But I hope to hear TheCBProject.

**Comment by covers1624** [comment]
This is purely cc loading it's custom data from disk and crashing, I'm devising a new storage system for this and ended sotragw that saves all the data to world nbt, this will be a 1.11 thing but depending on how breaking the change is I'll probably back port it to 1.10.

**Comment by EmanYm** [comment]
>MultiStorage
QuantumStorage
StorageDrawers
refinedstorage
rebornstorage
storagedrawrsextras

Do you really need six storage mods?  I haven't even bothered checking the rest.  You have around 175 (give-or-take) mods/plugins.  There is bound to be a conflict somewhere.

**Comment by mkrtes** [comment]
@covers1624 I have to admit I tried to delete the data of the mod (/chickenchunks folder in /world). It has not brought result.
@EmanYm It's modpack... I'm not the author ) But yeah, I also think it is overloaded.

**Comment by EmanYm** [comment]
Have you tried removing the file from the mods folder?  it will keep putting the configs back until the mod is gone.
Out of curiosity, which mod pack is it?

**Comment by covers1624** [comment]
Either way, this shoulsnt be happening, I'm out of the house so I can't fix this issue or check the code, from the looks of the crash this isn't what I first suspected it was.

**Comment by mkrtes** [comment]
@EmanYm [ResonsntRise by ATLauncher](https://www.atlauncher.com/pack/ResonantRiseDev)

**Comment by mkrtes** [comment]
I will add this information. I reinstall mod. Place chunkloader. The server worked fine, but after reboot the situation repeated. Here is the console log with the error. (In addition to the crash report.)
https://pastebin.com/hPYpA6Pf

**Comment by mkrtes** [comment]
So, can you help me?

**Comment by mkrtes** [comment]
So? 
https://gist.github.com/mkrtes/630ec398ab681a402d54e6d6009272a7

**Comment by covers1624** [comment]
Im looking in to rewriting the back end of CC for 1.11 this week, Probably tonight actually.

**Comment by covers1624** [comment]
Should be fixed in dev, i rewrote almost the entire backend.
