### ISSUE TITLE
Allfine with your mod

### ISSUE THREAD

**Issue by KarstenK77** [TheCBProject/ChickenChunks#17]
Sorry wrong report.

Regards, Drarcon.

**Comment by DR4RCON** [comment]
> ChickenChunks depends on CodeChickenCore, but that is now integrated in CodeChickenLib and so not compatible anymore with current CodeChickenLib. Any workaround?
> 
> CodeChickenLib-1.10.2-2.5.9.283-universal.jar



> ChickenChunks depends on CodeChickenCore, but that is now integrated in CodeChickenLib and so not compatible anymore with current CodeChickenLib. Any workaround?
> 
> CodeChickenLib-1.10.2-2.5.9.283-universal.jar

y
