### ISSUE TITLE
[1.10.2] Leaking world..?

### ISSUE THREAD

**Issue by DeadSix27** [TheCBProject/ChickenChunks#19]
Not sure if you still support 1.10, but when I run:
```
CodeChickenLib-1.10.2-2.5.9.308-universal.jar
CodeChickenCore-1.10.2-2.4.1.103-universal.jar
ChickenChunks-1.10.2-2.2.0.59-universal.jar
```
on Forge version: 12.18.3.2488

I run into leaks of the world.
It's actually relatively easy to reproduce, by using the above mods and forge version and then starting a new world with this specific seed: -4472807943775479860 (and many others, but this one's a tested example)

EDIT: Nvm, it's not that easy to reproduce.. It's like 1 in 3 world's generated have the leaking issue, not really tied to the seed..
But you can also try: -9046204886012486159
```
[08:15:38] [Server thread/DEBUG] [FML/]: The world 2e187f5e (world) may have leaked: first encounter (5 occurrences).
[08:15:38] [Server thread/DEBUG] [FML/]: The world 69b6a528 (world) may have leaked: first encounter (5 occurrences).
```

Not sure if you know what causes this, if there is a fix or whether I should worry about it.

Full log: https://gist.github.com/DeadSix27/1563e8ccda6c551ae619061692440789

**Comment by covers1624** [comment]
Yeah 1.10 isn't supported anymore, can you try with an earlier version of CCL just out of curiosity, Previous version should be fine. Are you also able to test on 1.12 and see if the issue persists?

**Comment by DeadSix27** [comment]
Earlier versions have the same issue

I tested on 1.12.2 with:
Forge: 14.23.0.2493
CodeChickenLib: 1.12-3.1.3.313
ChickenChunks: 1.12-2.4.0.70

And I can not get any leaks happening.. at least in the amount of tries I did....

**Comment by covers1624** [comment]
If someone is able to get me a JVM heap dump with this issue happening that would be amazing. This should be easy to do with VisualVM or with [Player's Sampler mod](https://minecraft.curseforge.com/projects/sampler) simply run `/sampler heapdump`, EIther way, the file might be quite large, depending on how much ram you have allocated to the server.
