### ISSUE TITLE
1.9 Dedicated server crash

### ISSUE THREAD

**Issue by xannor** [TheCBProject/ChickenChunks#2]
It seems that ChickenChunks is unloading Dimension 0 which will cause a dedicated server to crash with and ArrayIndexOutOfBounds: 0 error if no other dimension is loaded, otherwise a crash will occur if a person in another dimension then attempts to return to the overworld. Removing ChickenChunks prevents this issue from occuring.

**Comment by covers1624** [comment]
Interesting, can I have the crash log on paste bin please?

**Comment by xannor** [comment]
I will have to re-enable it to generate the logs, as i have been cleaning them up after each run, as I was setting up the server. I can do that later today. In the meantime I will try to give you as much information as I can remember. 

I felt that the log was fairly useless, the error was the ArrayIndexOutOfBounds: 0, and the stack trace was only MinecraftServer.run and one other step in the crash report and the log its self just showed that Dimension 0 was unloaded then a data freeze and then the shutdown events. The only way I was able to determine it was ChickenChunks was that I was progressively disabling and running mods and once I disabled ChickenChunks them the problem went away. I even re-enabled all other mods I had removed and it still worked.

It seems to take a couple of minutes after server load, or the last player exits for this to occur on dedicated. I had also got a similar error, same out of bounds, in single player when I was in the nether for a bit and then returned to the overworld.

**Comment by covers1624** [comment]
Hmm, i cannot reproduce this in dev.. http://puu.sh/omJ5R/e1a337e714.png A log will really help.

**Comment by covers1624** [comment]
@xannor can you try with this build http://chickenbones.net/maven/codechicken/ChickenChunks/1.9-2.0.1.26/

**Comment by xannor** [comment]
Looks to be running solid. I haven't tested dimension changing since I had to reset my world with the last round of mod updates (hence why I am trying out a dedicated server now,) I think it was the same issue so it should be solved as well.

**Comment by covers1624** [comment]
Cool, update will be on curse soon.

**Comment by christate** [comment]
FWIW, I was also having issues with the overworld not being loaded upon exiting the Nether [and the game crashing horribly], and now that I've updated to this new ChickenChunks drop, that is no longer happening.  \o/

**Comment by covers1624** [comment]
Yeah my derp, forge changed dim stuff and I forgot about it..
