### ISSUE TITLE
1.12 game crash

### ISSUE THREAD

**Issue by masterterp** [TheCBProject/ChickenChunks#21]
I was loading minecraft and was unable to due so because it was failing due to chicken chunks. 

Forge 1.12.2 - 14.23.1.255
Chicken chunks: 1.12.2-2.4.1.71-deobf

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ChickenChunks (chickenchunks)

[2018-01-13-3.log.gz](https://github.com/TheCBProject/ChickenChunks/files/1628858/2018-01-13-3.log.gz)

**Comment by covers1624** [comment]
That is the incorrect log file. Please upload the crash report.

**Comment by covers1624** [comment]
oh wait, You are using the `deobf` version of ChickenChunks, that is for mod developers, you need the `universal` jar.
