### ISSUE TITLE
ChickenChunks v2.4.1.71 Forced chunks do not get loaded upon server startup

### ISSUE THREAD

**Issue by Fatmice** [TheCBProject/ChickenChunks#22]
Per title, forced chunks are not automatically added to the active chunk list on server start until you walk near the area where the chunk loader was placed.  I only notice this because I placed my dragon egg mill (Extra Utility 2) to provide GP for my angel wings for flight power.  I happen to log out and shutdown server far from where the forced chunk containing the mill was located.  When server started back up and I log in, I was not able to fly until I went near the forced chunk again.  After that it stays loaded.

Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-b163786
SpongeForge: 1.12.2-2586-7.1.0-BETA-2873
Minecraft Forge: 14.23.1.2586

and many other mods.

**Comment by covers1624** [comment]
I can guarantee that this is not the case. They work fine. It could have been a sponge issue, but this is ancient so please open a new issue if this happens again.
