### ISSUE TITLE
Chunk Loaders Do Not Load Chunks

### ISSUE THREAD

**Issue by john01dav** [TheCBProject/ChickenChunks#23]
Hello,

I currently run a server running the Direwolf20 1.12 modpack. One of the mods in this pack is ChickenChunks, and this mod is having an issue. Placing chunk loaders in the deep dark, and almost certainly other dimensions, does not load the chunks. When placed, the chunk loader's ball does not spin. I tried moving the chunk loader to the overworld, where the ball also did not spin. When the issue first occurred, the chunk loader had a redstone signal applied to it. Removing the redstone signal has no effect. I tried re-generating the ChickenChunks.cfg file, as suggested [here](https://github.com/Chicken-Bones/ChickenChunks/issues/13), which also did not work. Furthermore, I ensured that the forgeChunkLoading.cfg file had plenty of allowed tickets and chunks, which also failed. The chunkloader shows up in neither /sampler chunkloaders, from the sampler mod, nor in /chunkloaders from chickenchunks. I am running Forge 1.12.2-14.23.1.2587-universal with Sponge 1.12.2-2555-7.1.0-BETA-2833 ChickenChunks 1.12.2-2.4.1.71-universal and CodeChickenLib 1.12.2-3.1.5.331-universal. What is the issue, and how can I fix it?

EDIT: I forgot to add that the adjusters for the radius in the gui work intermittently, and the lasers, when enabled, have their base move as if they were following a hypothetical moving ball.

Thank you

**Comment by covers1624** [comment]
Can i have your full log file from the server side, directly after attempting to place a ChunkLoader please.

**Comment by john01dav** [comment]
There are no log messages whatsoever fron anything vaguely chicken chunks
related or temporally correlated with the placement.

**Comment by covers1624** [comment]
I'm still going to need the log file, i can assure you ChickenChunks loads chunks, it could be sponge breaking it some how, it could be some exception being thrown inside ChickenChunks, who knows, only the log can tell me this. Also just to make sure, you aren't providing a redstone signal the the ChunkLoader by any chance?

**Comment by john01dav** [comment]
Alright, I'll yet the log file tomorrow (I need to stop procrastinating on
sleep). As for the redatone signal, placing it in the middle of an empty
chunk doesn't fix this, and all players I asked have the same issue.

**Comment by covers1624** [comment]
No log was provided, and i can guarantee that ChunkLoaders load chunks. Closing this as it it ancient.
