### ISSUE TITLE
Mobs not Spawn

### ISSUE THREAD

**Issue by Nitrama** [TheCBProject/ChickenChunks#24]
Mobs from Spawner not Spawn.

**Comment by covers1624** [comment]
Chicken chunks doesn't have any spawners.. Nor does the ChunkLoader spawn entities. What are you refering to exactly?

**Comment by covers1624** [comment]
If you are referring to vanilla spawners not spawning mobs when chunk loaded, the player needs to be near the spawner for it to spawn mobs.

**Comment by Nitrama** [comment]
Yes that's what I meant

**Comment by covers1624** [comment]
Figured, Vanilla mechanic, the player must be within range of the spawner for it to spawn mobs. Nothing i can do sorry.
