### ISSUE TITLE
awayTimeout only considers login time

### ISSUE THREAD

**Issue by Ricket** [TheCBProject/ChickenChunks#25]
`awayTimeout` checks the last login time of a player to consider whether to keep a chunk loader going or not. Shouldn't it always keep the chunk loader enabled while the player is logged in, and start the timer once the player logs out? As it's implemented now, if I set `awayTimeout` to 30, then someone logs in, their chunk loaders start working, 30 minutes later they stop working even if the player is still logged in. That doesn't seem very useful...

**Comment by covers1624** [comment]
I'm unable to reproduce this.
