### ISSUE TITLE
[1.12.2] SP Server-Side Crash - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by jdawg3636** [TheCBProject/ChickenChunks#26]
Server-side crash when loading my SP World - looks to have something to do with using an advanced for loop to modify a `LinkedList` whilst it is being iterated over.

Crash Report Excerpt (Let me know if the full log is necessary): https://pastebin.com/3XbcsxgZ

Game Version: 1.12.2
ChickenChunks Version: 2.4.1.71

**Comment by covers1624** [comment]
Someone is adding chunk loading tickets on a thread. there is nothing i can do about this, remove mods until you find the culprit.
