### ISSUE TITLE
Minecraft closes as soon as I try to load my game

### ISSUE THREAD

**Issue by yago56037** [TheCBProject/ChickenChunks#27]
Hi, I've been having this trouble recently and it seems that is caused by the ChickenChunks mod. 
Here's the crash report:
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 9/07/18 11:36
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
	at codechicken.chunkloader.ChunkLoaderManager.load(ChunkLoaderManager.java:496)
	at codechicken.chunkloader.ChunkLoaderEventHandler.onWorldLoad(ChunkLoaderEventHandler.java:56)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_395_ChunkLoaderEventHandler_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService$GameProfileSerializer.deserialize(YggdrasilAuthenticationService.java:116)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService$GameProfileSerializer.deserialize(YggdrasilAuthenticationService.java:1)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at com.google.gson.Gson$1.deserialize(Gson.java:126)
	at com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse$Serializer.deserialize(ProfileSearchResultsResponse.java:44)
	at com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse$Serializer.deserialize(ProfileSearchResultsResponse.java:1)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:75)
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:53)
	at net.minecraft.server.management.PlayerProfileCache.func_152650_a(PlayerProfileCache.java:93)
	at net.minecraft.server.management.PlayerProfileCache.func_152655_a(PlayerProfileCache.java:179)
	at codechicken.core.ServerUtils.getGameProfile(ServerUtils.java:80)
	at codechicken.core.ServerUtils.isPlayerOP(ServerUtils.java:84)
	at codechicken.chunkloader.ChunkLoaderManager.allowOffline(ChunkLoaderManager.java:582)
	at codechicken.chunkloader.ChunkLoaderManager.loadPlayerChunks(ChunkLoaderManager.java:543)
	at codechicken.chunkloader.ChunkLoaderManager.load(ChunkLoaderManager.java:492)
	... 8 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 329239128 bytes (313 MB) / 1009778688 bytes (963 MB) up to 2386034688 bytes (2275 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2560m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 80 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAA	Forge{10.13.4.1492} [Minecraft Forge] (modpack.jar) 
	UCHIJAA	CodeChickenCore{1.0.6.41} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.4.102} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.102-universal.jar) 
	UCHIJAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAA	mcdiscord{2.0.0} [MC Discord] (minecraft.jar) 
	UCHIJAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303 (1).jar) 
	UCHIJAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHIJAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHIJAA	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHIJAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHIJAA	ComputerCraft{1.74} [ComputerCraft] (ComputerCraftPlusComputerCraftEdu1.74.jar) 
	UCHIJAA	IC2{2.2.999} [Industrial Craft Classic] (IC2.Classic.Version.1.1.3.5.jar) 
	UCHIJAA	Forestry{3.6.11.2} [Forestry for Minecraft] (forestry_1.7.10-3.6.11.2.jar) 
	UCHIJAA	LogisticsPipes{0.9.3.70} [Logistics Pipes] (logisticspipes-0.9.3.70.jar) 
	UCHIJAA	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.0.jar) 
	UCHIJAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAA	asielib{0.4.4} [asielib] (AsieLib-1.7.10-0.4.4.jar) 
	UCHIJAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAA	bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
	UCHIJAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAA	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) 
	UCHIJAA	bluepower{0.2.962} [Blue Power] (BluePower-1.7.10-0.2.962-universal.jar) 
	UCHIJAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHIJAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHIJAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHIJAA	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UCHIJAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-Mod-1.7.10-Recommended.jar) 
	UCHIJAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0 (1).jar) 
	UCHIJAA	ComputerCraftEdu{1.74} [ComputerCraftEdu] (ComputerCraftPlusComputerCraftEdu1.74.jar) 
	UCHIJAA	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UCHIJAA	computronics{1.5.7} [Computronics] (Computronics-1.7.10-1.5.7.jar) 
	UCHIJAA	defaultkeys{1.0.24} [Default Keyconfig] (defaultkeys-mc1.7.10-1.0.24.jar) 
	UCHIJAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAA	eng_toolbox{1.2.3.0} [Engineer's Toolbox] (EngineersToolbox-1.2.3.0-BETA.jar) 
	UCHIJAA	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UCHIJAA	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UCHIJAA	gendustry{1.6.1.126} [GenDustry] (gendustry-1.6.1.126-mc1.7.10.jar) 
	UCHIJAA	IC2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper] (IC2.Classic.Version.1.1.3.5.jar) 
	UCHIJAA	IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2] (IC2NuclearControl-2.3.3a-Exist.jar) 
	UCHIJAA	ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar) 
	UCHIJAA	ImmibisPeripherals{59.0.2} [Immibis's Peripherals] (immibis-peripherals-59.0.2.jar) 
	UCHIJAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJAA	IronChest{6.0.60.741} [Iron Chest] (Ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAA	itlt{0.0.8} [It's the little things] (itlt-1.7.10-0.0.8.jar) 
	UCHIJAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAA	millenaire{6.0.1} [Millénaire] (millenaire-6.0.2.jar) 
	UCHIJAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10.jar) 
	UCHIJAA	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	UCHIJAA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHIJAA	powersuits{0.11.0.293} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.293.jar) 
	UCHIJAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAA	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAA	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAA	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCHIJAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJAA	OCS{1.7.5} [OpenCCSensors] (openccsensors-1.7.5.jar) 
	UCHIJAA	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.1.jar) 
	UCHIJAA	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UCHIJAA	ProjectE{1.7.10-PE1.9.3} [ProjectE] (ProjectE-1.7.10-PE1.9.3h.jar) 
	UCHIJAA	quiverchevsky{b100} [QuiverBow] (QuiverBow_1.7.10_b100.zip) 
	UCHIJAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAA	JAKJ_RedstoneInMotion{2.8.8} [Remain In Motion] (RemainInMotion-2.8.8.jar) 
	UCHIJAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAA	TF2Teleporter{1.7.10} [TF2 Teleporter] (TF2Teleporter-1.7.10.jar) 
	UCHIJAA	Tubestuff{59.0.4} [Tubestuff] (tubestuff-59.0.4.jar) 
	UCHIJAA	zettaindustries{1.1} [Zetta Industries] (zettaindustries-1.1-105.jar) 
	UCHIJAA	aobd{2.8.4} [Another One Bites The Dust] (AOBD-2.8.4.jar) 
	UCHIJAA	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	CoFHCore: -[1.7.10]3.0.3-303
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.1-89
	List of loaded APIs: 
		* apAPI (2) from additionalpipes-4.7.0.jar
		* asielibAPI (1.1) from AsieLib-1.7.10-0.4.4.jar
		* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.4.4.jar
		* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.4.4.jar
		* asielibAPI|tool (1.1) from AsieLib-1.7.10-0.4.4.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* bluepowerAPI (1.0) from BluePower-1.7.10-0.2.962-universal.jar
		* BotaniaAPI (76) from Botania r1.8-249.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|blueprints (1.2) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|boards (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|core (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|events (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|fuels (2.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|gates (4.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.7.0.0.jar
		* BuildCraftAPI|library (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.14.jar
		* BuildCraftAPI|recipes (2.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|statements (1.0) from Railcraft_1.7.10-9.7.0.0.jar
		* BuildCraftAPI|tablet (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.7.0.0.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.7.0.0.jar
		* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.7.0.0.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
		* CoFHAPI (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|block (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHAPI|core (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from RemainInMotion-2.8.8.jar
		* CoFHAPI|fluid (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|inventory (1.7.10R1.0.1) from buildcraft-compat-7.1.3.jar
		* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHAPI|modhelpers (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|tileentity (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|transport (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* ComputerCraft|API (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|FileSystem (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Lua (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Media (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Peripheral (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Permissions (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Redstone (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Turtle (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* computronicsAPI (1.3) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|chat (1.3) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|multiperipheral (1.1) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|tape (1.0) from Computronics-1.7.10-1.5.7.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.11.2.jar
		* gendustryAPI (2.2.0) from gendustry-1.6.1.126-mc1.7.10.jar
		* IC2API (1.0) from IC2.Classic.Version.1.1.3.5.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.3.3a-Exist.jar
		* ProjectEAPI (7) from ProjectE-1.7.10-PE1.9.3h.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|carts (1.3.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|core (1.3.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|crafting (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|events (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|helpers (1.1.0) from EngineersToolbox-1.2.3.0-BETA.jar

**Comment by yago56037** [comment]
By the way, I'm playing on the 1.7.10 version

**Comment by covers1624** [comment]
Sorry 1.7 is not supported anymore. But the issues seems to be the profile cache stored by the mc server. The file should be called `usercache.json` or `usernamecache.json`, delete the file and try again.
