### ISSUE TITLE
Multiplayer crash only when 2 people logged in.

### ISSUE THREAD

**Issue by tysonhoffman** [TheCBProject/ChickenChunks#28]
I have been trying to figure out whats causing this crash to occur.

I have a minecraft server setup and my daughter can log in on her laptop and play all day without a single crash.  If I am logged in and playing on my laptop and she attempts to log in it crashes.

If she is logged in and I log in she crashes.  She can be logged in playing by herself with no issues all day.  

I have 3 other people that play on the server and there are no issues.  I can play with them and they can play with her.  But we crash each other.  I am so confused.

I have attached a log file from the crash.  Any help would be hugely appreciated.
[crash-2018-08-14_17.13.35-client.txt](https://github.com/TheCBProject/ChickenChunks/files/2288772/crash-2018-08-14_17.13.35-client.txt)

**Comment by covers1624** [comment]
This is actually a crash in some error handling i have for CCL, CCL can catch exceptions thrown whilst rendering another mod's block, there seems to be some quirks with method reference lambdas in java. Also i have no idea why you opened this on the ChickenChunks repo.. Anyway, https://github.com/TheCBProject/CodeChickenLib/commit/25929ca771c14bd068492ceaabe8a95e7446c82e should fix it, pushing an immediate release.

**Comment by tysonhoffman** [comment]
Sorry I saw CodeChicken and just thought this would be the right place.  I really appreciate you taking the time.  Its something me and my daughter started and she is so excited!
