### ISSUE TITLE
[Feature Request] Can you update ChickenChunks to Forge 2062+

### ISSUE THREAD

**Issue by ghost** [TheCBProject/ChickenChunks#3]
Hi Cover

Cheers of the amazing effort maintaining ChickenBones Mods.
Can you be kind enough to bump ChickenChunks to work with "Capabilities for World" introduced in Forge 2062+ for MC 1.10.2

**Comment by covers1624** [comment]
What do you mean, just bump the version of forge I use? Implement in world caps?

**Comment by ghost** [comment]
Implementing world capabilities would be great. I take it that you have to bump forge as well if you are doing that.

**Comment by covers1624** [comment]
World caps really don't make much sense in my opinion..
