### ISSUE TITLE
Random Crash 

### ISSUE THREAD

**Issue by angelnc1989** [TheCBProject/ChickenChunks#31]
Minecraft 1.12.2
Forge 14.23.4.2762
ChickenChunks 1.12.2-2.4.1.73-universal
CodeChickenLib 1.12.2-3.2.2.353-universal

https://pastebin.com/h6fLm2nk

My game started crashing randomly yesterday. Sometimes it takes only a few minutes sometimes hours. I can't narrow it down to anything specific happening.

**Comment by covers1624** [comment]
I can't seem to figure out why this would even happen, its litrelly not possible. Please comment if this issue happens again.
