### ISSUE TITLE
Strange Chicken Chunks Chunkloader Behavior in RFTools Dimensions

### ISSUE THREAD

**Issue by Xiathan** [TheCBProject/ChickenChunks#34]
Issue description: Chicken chunks chunkloaders do not work in RFTools dimensions under some circumstances. If a dimension is dialed once, traveled to, and then left by use of a charged porter, the chunkloader in the dialed dimension works as expected. If the dimension is left dialed indefinitely, however, the chunkloader does not function upon return to the overworld. Traveling back to the dimension, the chunkloader pearl animation has stopped. The chunkloader from Chicken Chunks works in other dimensions like the nether and the end, so I'm not sure if it's something weird with RFTools Dimensions.

Steps to reproduce: Create dimension. Dial (but do not "dial once") and travel. Place a chunkloader from chicken chunks, and use something that can check if dimension is still loaded (ie. a builder with quarry card and item transport back to overworld). Travel back to overworld with charged porter. Quarry should no longer be functioning.

Versions:

Minecraft: 1.12.2
Forge: 2768
McJtyLib: 3.0.7
RFTools: 7.59
RFTools Dimensions: 5.63
CodeChickenLib: 3.2.2.353
ChickenChunks: 2.4.1.73

**Comment by covers1624** [comment]
If the pearl is not spinning then the chunk loader is inactive and is not loading any chunks. Its likely that RF Tools is force unloading the dimension or something of the sorts. @McJty Thoughts?

**Comment by covers1624** [comment]
Old issue, 1.12 is not supported anymore.

If you still experience issues in 1.16+ please let me know.
