### ISSUE TITLE
Chunks aren't loading chunks at all

### ISSUE THREAD

**Issue by smellypengu** [TheCBProject/ChickenChunks#35]
There are no errors or anything in the console and I've tried everything to get this mod to work.
I need this mod to chunk load my nether lava farming. But nothing is happening with a chunk loader or a spot loader.

**Comment by tannisroot** [comment]
I have the same issue sadly :(

**Comment by covers1624** [comment]
It appears I have forgotten about this issue.

If this issue persists in 1.16+ please let me know.
