### ISSUE TITLE
FTB Utilities Not Chunk Loading Properly

### ISSUE THREAD

**Issue by JustChasee** [TheCBProject/ChickenChunks#36]
Playing in a singler player world, I have a mob farm (mob crusher) killing mobs spawned in on cursed earth, I have their loot going into a ender chest that is linked to another ender chest in my base. While at mob farm loot is being transferred from mob farms chest to base chest but once i get to my base its like the chunk is not loaded. Even tried linking up storage from mob farm to base with just transport pipes from Ender IO but nothing. It's like ftb utilities chunk loader is not working. Please Help.

**Comment by gigabit101** [comment]
This needs reporting to the FTB utility guys and not here
