### ISSUE TITLE
chunkloader doesnt work

### ISSUE THREAD

**Issue by Terrarion111** [TheCBProject/ChickenChunks#38]
my chunkloader doesnt work since a few days i hope any one can answer me (sorry for my english)

**Comment by covers1624** [comment]
Gonna beed more information, single player? Multiplayer? What does /chunkloaders show you, can i have a screen shot of /chunkloaders?

**Comment by Terrarion111** [comment]
single player i dont know how to send a screenshot but the chunkloader looks normal the ball is spinning the only think is that the chunks are not loading

**Comment by covers1624** [comment]
Unfortunately, it appears I forgot about this issue..

If this issue still persists in 1.16+ please let me know.
