### ISSUE TITLE
Chunk Loader stuck at 1 chunk

### ISSUE THREAD

**Issue by HiddenAbilitree** [TheCBProject/ChickenChunks#39]
The chunk loader is just stuck at 1 chunk.
![Screenshot (320)](https://user-images.githubusercontent.com/59267569/71493324-c5698680-280b-11ea-8907-74c31017798d.png)

**Comment by HiddenAbilitree** [comment]
i cant make it go higher than 1 chunk.

**Comment by overpolish** [comment]
Was there a solution for this issue? Currently experiencing the same thing.

**Comment by covers1624** [comment]
This is an incredibly old issue, with no information other than a screenshot.

If this issue persists in 1.16+ please let me know.
