### ISSUE TITLE
Chicken Chunks not loading in the Nether

### ISSUE THREAD

**Issue by JosiahpMartin** [TheCBProject/ChickenChunks#4]
Hi covers,

The chunk loader and spot loader are only working in the overworld.  I've successfully used extra utilities chunk ward and it it is working so I don't think it is a forge issue.  Using the command "chunkloaders" shows chicken chunk loaders active in the overworld, however, it does show chunk loaders from other mods in other dimensions. If you need any more information feel free to ask.

[fml-client-latest.txt](https://github.com/TheCBProject/ChickenChunks/files/537750/fml-client-latest.txt)

**Comment by covers1624** [comment]
Haven't herd of this happening in ages, if it happens again open a new issue.
