### ISSUE TITLE
chunkloader stops working

### ISSUE THREAD

**Issue by Sh0wYaH0wda** [TheCBProject/ChickenChunks#41]
so i play singleplayer 1.12.2 and when i close the game and reopen the chunkloader in the nether stops working and the little ball that spins doesnt spin and just sits ontop the chunkloader. 
![2020-01-31_21 23 34](https://user-images.githubusercontent.com/40673661/73585575-6208ef00-4470-11ea-839c-6025051b0b1f.png)

**Comment by covers1624** [comment]
You have the chunk loader next to an active lever, it is redstone controlable.

**Comment by DoGSh0wYaH0wda** [comment]
ive also had it a couple blocks away and still have the issue

**Comment by Sh0wYaH0wda** [comment]
ah i see didnt know that although could have sworn i had it farther than 2 blocks away from the lever the first time. but i moved it and it doesnt seem to stop working anymore. sorry for the inconvenience
