### ISSUE TITLE
Chickenchunks, players are still working offline

### ISSUE THREAD

**Issue by EnterFor** [TheCBProject/ChickenChunks#42]
My config:
`#ChunkLoader Configuration File
#Deleting any element will restore it to it's default value

#Per player chunk limiting. Values ignored if 0.:Simply add <username>=<value>
players
{
	#Forge gives everyone 12500 by default
	DEFAULT=10
	#For server op's only.
	OP=5000
}

#If set to false, players will have to be logged in for their chunkloaders to work.:Simply add <username>=<true|false>
allowoffline
{
	DEFAULT=false
	OP=false
}

#Set to false to deny a player access to the chunk viewer
allowchunkviewer
{
	DEFAULT=true
	OP=true
}

#The number of minutes since last login within which chunks from a player will remain active, 0 for infinite.
awayTimeout=1

#Sets lasers to render as an outline instead of a solid square.
lasersRenderHollow=false

#The maximum number of chunks per chunkloader
maxchunks=1

#Enabling this lets OPs alter other player's chunkloaders. WARNING: If you change a chunkloader, you have no idea what may break/explode by not being chunkloaded.
op-interact=true

#Set to false to disable the automatic reloading of mystcraft dimensions on server restart
reload-dimensions=true
`
Mod version: Chicken Chunks 1.12.2-2.4.2.74-universal
Forge:2847
Server：CatServer-universal

Chickenchunks, players are still working offline
If it's a catserver problem, please let me know and I'll give feedback.
Sorry, my English is not good. I'm Chinese

**Comment by EnterFor** [comment]
Are you still maintaining this project?
I've been expecting to hear from you

**Comment by covers1624** [comment]
Unfortunately, I never got around to looking into this before 1.12 became unsupported.

If your issues still exist in 1.16+, please let me know.
