### ISSUE TITLE
Possible bug: Redstone signal update not triggered until GUI update

### ISSUE THREAD

**Issue by vexedred2019** [TheCBProject/ChickenChunks#45]
Hi, I was testing ChickenChunks in a single player creative world before deploying it to two private SMP servers I run, and I noticed an odd behaviour. When applying a redstone signal to stop chunkloading, it has no effect until I open the chunkloader GUI, and change the range. Same thing for removing the signal.

After noticing this in a modpack test environment, I replicated it in a clean install:

Forge 1.12.2-14.23.5.2847
CodeChicken Lib 1.12.2-3.2.3.358
ChickenChunks 1.12.2-2.4.2.74

It's a great mod, and I'll be sad if it doesn't migrate to 1.14/1.15 but happy to keep using it on 1.12.2 while we're still waiting for a full suite of content mods. Fine grained chunkloading of this sort is hard to find. It's just that the ability to switch off loading is really useful, and if we have to go into the GUI as well as flip a lever to trigger the switch, it kind of undermines its value. If I'm missing something at my end, please advise.

**Comment by vexedred2019** [comment]
Also, a chunkloader that has been disabled using RS signal and the GUI change workaround before a world close, is active again (despite still receiving the signal) after a world restart. In SMP this means every chunkloader would need to be manually pinged in game after every restart. Ugh.

**Comment by covers1624** [comment]
This bug has been resolved in a pending update for 1.16.

**Comment by covers1624** [comment]
Version `2.9.0.87` has now been released which should resolve this issue.
