### ISSUE TITLE
High tick usage from WorldTickEvent handler

### ISSUE THREAD

**Issue by clienthax** [TheCBProject/ChickenChunks#46]
ChickenChunks-1.12.2-2.4.2.74-universal.jar

![image](https://user-images.githubusercontent.com/1056270/79157602-c92a1480-7dcc-11ea-97f4-a3a7ce267ede.png)

**Comment by covers1624** [comment]
This issue has been resolved in the complete rewrite ChickenChunks received in 1.15+.
