### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by Akai1** [TheCBProject/ChickenChunks#5]
https://gist.github.com/Akai1/d6402fff2c83e1cf5180c40dc8a5ef52

**Comment by covers1624** [comment]
Delete your enderstorage config.

**Comment by Akai1** [comment]
@covers1624 Still [same crash](https://gist.github.com/Akai1/5ae5bd950ca681a96b57a372b4765507) after deleting the enderstorage config file.

**Comment by Akai1** [comment]
Deleted the entire config folder and still crashing with latest versions: https://gist.github.com/Akai1/f3f884272243b74def1964fac68591f3

**Comment by covers1624** [comment]
Something is stopping enderstorage from creating a config file. 
Would you be able to translate the end of this "java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\Akai\Desktop\Modpacks\1.10.2\config\EnderStorage.cfg (Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar)"

**Comment by Akai1** [comment]
The operation is not applicable to a file with an open area associated with a user.

**Comment by Akai1** [comment]
Tried with latest [ChickenChunks](https://gist.github.com/Akai1/9631bc4eb120e149d228367fdf1a096e) and [EnderStorage](https://gist.github.com/Akai1/e6c7bbf31f953206ffe44ac5d45f2734) and still crashes.

**Comment by covers1624** [comment]
This was an EnderStorage issue, 99 percent sure this is a user issue / fluke.
