### ISSUE TITLE
Could not pass NotifyNeighborBlockEvent$Impl Error

### ISSUE THREAD

**Issue by MrKiel** [TheCBProject/ChickenChunks#50]
Hi, 

We had to remove chunkloaders from our world due to the mod not correctly respecting player activity (specifically, the mod would load chunks whether or not a player was on, leading to hundreds of busy chunks staying loaded 24/7). 

First, we removed the mod and loaded the world, to remove all blocks from the mod. 
Next, we added the mod back into the /mods/ folder and started the world, but encountered the errors attached. 

We had to leave the mod out for the time being, but would eventually like to include it again. I fear we may have to reset the world in order to do so however (which we're not planning to do for months). 

Can you offer any support in this instance please?

[crash-2020-08-11_20.12.26-server.txt](https://github.com/TheCBProject/ChickenChunks/files/5059471/crash-2020-08-11_20.12.26-server.txt)
[2020-08-11-7.log](https://github.com/TheCBProject/ChickenChunks/files/5059473/2020-08-11-7.log)
[crash-2020-08-11_20.01.33-server.txt](https://github.com/TheCBProject/ChickenChunks/files/5059474/crash-2020-08-11_20.01.33-server.txt)

**Comment by covers1624** [comment]
ChickenChunks has config options to turn off a users ChunkLoaders when they go offline fyi.
As for this crash, it appears IC2 a chunk load callback, then it causes a neighbor chang event to propogate through a few things, ultimately causing a crash, it shouldnt be firing that neighbor change. SpongeForge is also installed, but im doubtfull that it is the cause..

**Comment by MrKiel** [comment]
I'm aware of the config option to stop loading chunks for players who are offline; unfortunately it has no effect. We have proven with 100% certainty that those chunks are still being loaded, despite the configuration being set otherwise. 

Thank you for your insight, there's not much we can do about it right now, we'll have to add the mod back in on next reset.

**Comment by covers1624** [comment]
Unfortunately, I didn't get to this issue before 1.12 became unsupported.

This has been resolved via the complete rewrite ChickenChunks received in 1.15+
