### ISSUE TITLE
Crash when radius set at 0

### ISSUE THREAD

**Issue by Beralath** [TheCBProject/ChickenChunks#51]
Hi, nothing more to say. When the loader is set at 0 radius, it crashes the server.

**Comment by covers1624** [comment]
Provide a crash report.

**Comment by Beralath** [comment]
https://pastebin.com/aHZ8fN2j

**Comment by TheOrionsun** [comment]
I have tried this on MC 1.15.2 Forge 31.2.36 and Chicken Chunks 1.15.2-2.5.0.77-universal. 
I did not have a Crash but I was unable to load my save after exiting.

**Comment by Beralath** [comment]
Actually, the crashes always happened at the reboot. I should have said that, sorry I forgot.

**Comment by covers1624** [comment]
This should be resolved by changes made in Forge to prevent these deadlocks. See: https://github.com/TheCBProject/ChickenChunks/issues/74
