### ISSUE TITLE
Crops not growing in chunk loaded area(minecraft 1.15.2)

### ISSUE THREAD

**Issue by p3rsik** [TheCBProject/ChickenChunks#52]
mod list:

> AI-Improvements-1.15.2-0.3.0.jar
> angelring-1.15.2-1.2.0.jar
> AppleSkin-mc1.15.2-forge-1.0.14.jar
> appliedenergistics2-7.0.0-beta.1.jar
> astralsorcery-1.15.2-1.12.3.jar
> BetterMineshaftsForge-1.15.2-1.3.jar
> Bookshelf-1.15.2-5.6.40.jar
> Botania-r1.15-388.jar
> Bountiful+Baubles-1.15.2-0.0.1.jar
> buildinggadgets-3.3.5.jar
> ChickenChunks-1.15.2-2.5.0.77-universal.jar
> Clumps-5.0.2.4.jar
> CodeChickenLib-1.15.2-3.3.1.379-universal.jar
> cofh_core-1.15.2-0.4.0b.jar
> comforts-FORGE-1.15.2-2.0.0.3.jar
> config-2-3.0.jar
> CraftingTweaks_1.15.2-11.0.1.jar
> CraftTweaker-1.15.2-6.0.0.24.jar
> Cucumber-1.15.2-3.0.9.jar
> curios-FORGE-1.15.2-2.0.2.6.jar
> DarkUtilities-1.15.2-3.1.8.jar
> deathquotes-1.15.1-1.0.jar
> elevatorid-1.15.2-1.7.1.jar
> EnchantmentDescriptions-1.15.2-2.0.9.jar
> EnderStorage-1.15.2-2.5.0.149-universal.jar
> endertanks-1.15-1.8.1.jar
> ensorcellation-1.15.2-0.4.1b.jar
> FastFurnace-1.15.1-3.0.0.jar
> FastLeafDecay-v22.jar
> FastWorkbench-1.15.2-3.1.1.jar
> Hwyla-forge-1.10.8-B72_1.15.2.jar
> Industrial+Agriculture[Botania]-1.15.2-1.7.0.jar
> Industrial+Agriculture[Core]-1.15.2-1.7.0.jar
> Industrial+Agriculture[Industrial+Foregoing]-1.15.2-1.6.1.jar
> Industrial+Agriculture[Mekanism]-1.15.2-1.6.1.jar
> industrial-foregoing-1.15.2-2.3.3-e356e61.jar
> infernalmobs-1.15.2.1.jar
> InventoryHud_1.15.2.forge-3.0.1.jar
> inventorysorter-1.15.2-17.0.0.jar
> invtweaks-1.15.2-2.0.8.jar
> ironchest-1.15.2-10.0.3.jar
> jei-1.15.2-6.0.2.12.jar
> JEIEnchantmentInfo-1.16.1-1.1.0.jar
> jeiintegration_1.15.2-3.1.0.1.jar
> JustEnoughResources-1.15.2-0.10.1.77.jar
> libnonymous-1.15.2-1.1.1.5.jar
> light-overlay-4.7.0.jar
> lycanitesmobs-1.15.2-2.2.3.2.jar
> Mekanism-1.15.2-9.10.9.422.jar
> MekanismAdditions-1.15.2-9.10.9.422.jar
> MekanismGenerators-1.15.2-9.10.9.422.jar
> MekanismTools-1.15.2-9.10.9.422.jar
> mining_dimension-1.15.2-1.0.4.jar
> Morpheus-1.15.2-4.2.50.jar
> MysticalAgriculture-1.15.2-3.0.9.jar
> NaturesAura-28.4.jar
> Neat+1.6-22.jar
> observerlib-1.15.2-1.2.0.v60.jar
> Patchouli-1.15.2-1.2-35.jar
> Placebo-1.15.2-3.1.0.jar
> preview_OptiFine_1.15.2_HD_U_G1_pre30.jar
> ScalingHealth-1.15.2-3.0.9+54.jar
> shetiphiancore-1.15-3.7.2.jar
> SilentLib-1.15.2-4.6.6+59.jar
> simplybackpacks-1.15.2-1.4.6.jar
> StorageDrawers-1.15.2-7.0.2.jar
> swingthroughgrass-1.15.2-1.4.0.jar
> switchbow-1.6.jar
> TerraForged-1.15.2-0.1.2.jar
> themidnight-0.5.9.jar
> tinyprogressions-1.15.2-4.0.8.jar
> titanium-1.15.2-2.4.2.jar
> tombstone-4.5.6.jar
> valhelsia_structures-15.0.3a.jar
> WailaHarvestability-mc1.15.2-1.1.12.jar
> WAWLA-1.15.2-3.0.4.jar
> Waystones_1.15.2-6.0.2.jar
> Xaeros_Minimap_20.18.0.1_Forge_1.15.2.jar
> xptome-1.15.2-v1.1.6.jar

I have a standard tree farm and farm with mystical agriculture crops. I have placed a chunkloader on my base, included farms in chunkloading radius and left for the night. The next evening, when I returned, I found out that all was working fine through the night, except farms. Plants just stopped growing.

**Comment by WraithHunter** [comment]
Having the same issue. tested with just Chicken Chunks loaded and had the same issue.

**Comment by Morpheus1101** [comment]
Tested this myself with a few various mods and was not able to re-produce this issue using default config.

**Comment by covers1624** [comment]
We are going to need more information on how you are reproducing this.
Are you in a modded dimension?
Are you on a multiplayer server?
Have you modified your config file?
Feel free to jump on the discord and chat about it: http://discord.gg/9nr3qyC

**Comment by WraithHunter** [comment]
Can't speak for the OP.
On my end reproduction was simply to create a new profile on twitch, minecraft version 1.15.2, forge version 31.2.9, install Chicken Chunks. Create a new flat world, plants seed and water in a chunk, throw down a chunk loader and tp ~10,000 blocks away and wait. regardless of wait time the seeds wouldn't grow. Also tested increasing random tick speed which also had no effect.

**Comment by covers1624** [comment]
Can you check if something like a command block, or an AE system keeps working in those chunks?

**Comment by WraithHunter** [comment]
I've tested a command block with a 'say' command connected to a repeater clock. Works as intended.

**Comment by covers1624** [comment]
Whilst crops aren't growing?

**Comment by WraithHunter** [comment]
Yup.

**Comment by covers1624** [comment]
Alright, sounds like the chunks are being forced, but random ticks aren't being fired. Fun..

**Comment by WraithHunter** [comment]
"Fun" Like a logic error in someone elses code. lol

**Comment by WraithHunter** [comment]
Just tested on a second system. problem persisted.

**Comment by Morpheus1101** [comment]
I was able to replicate on 1.15.2 & 1.16.1

**Comment by covers1624** [comment]
Can someone try with [forceload](https://minecraft.gamepedia.com/Commands/forceload) instead of a ChunkLoader?

**Comment by Morpheus1101** [comment]
1.15.2 Made no Difference

**Comment by covers1624** [comment]
Appears to be a vanilla mechanic, only chunks loaded by players will have 'chunk ticks' fired.
Reference: `ServerChunkProvider.tickChunks()` ln 356, `ChunkManager.isOutsideSpawningRaduis`(terrible name, should be `isPlayerLoading`)

**Comment by Kadwen01** [comment]
I think this might be more then just Crops.    I got a 1.15 world as well and found that my Ranged Pump is not pumping Lava from the Nether to the Overworld (via ender tanks).   I got a chunk loader at the base as well as the pump.   I have to keep popping into the nether to get the pump to dump into the ender tank. then return to the overworld to feed it into a "storage" tank so my generator has fuel.

**Comment by madappe** [comment]
I am new to github, was in search of some prlobem solving. I am trying to build my own pack on 1.15.2. and discovered that my chunk loader does not work in the Nether as @Kadwen01 said it above. First I tought its the ender tank or the ranged pump, but its def the chunk loader not loading if i am not in the nether. i def did not change any configs on any mods.

**Comment by TheOrionsun** [comment]
I noticed WraithHunter  states they are using Forge 31.2.9. I have other mods that when forge is loading them it tells me there is a newer Forge version. When looking at the Current Modloader Versions Forge 31.2.9 is at the top of the list, but I think it is an older version. Forge 31.2.36 has worked for me. I looks like the list is moving .4 to .9 to the top, but they are older and the list is not in the correct release order.

You may want to try Forge 31.2.36 and see if there is still an issue....

**Comment by Morpheus1101** [comment]
This has all ready been tested on 31.2.36 and confirmed and tagged by covers as a legit bug hence requiring no more testing on this particular issue currently.

**Comment by Letoric** [comment]
Just a heads up, the mod "Chonk" has random ticks working in 1.16.x in case looking at that source ( https://github.com/Memebeams/Chonk ) gives you some insight. I know Lat looked at it and made some changes to FTB chunk loader, but random ticks still don't seem to fire with his right now.

**Comment by covers1624** [comment]
Yeah no, I'm not doing what they do, https://github.com/Memebeams/Chonk/blob/master/src/main/java/com/memebeams/chonk/chunkloading/ChunkManager.java#L96
Ill submit a proper PR to Forge and have things work properly out of the box.

**Comment by ghost** [comment]
Hi @covers1624, any chance that we can get a new release soon now that this has been fixed? Thanks and appreciate your work on this mod!
