### ISSUE TITLE
Unable to pickup Chunk Loader after placing

### ISSUE THREAD

**Issue by TheOrionsun** [TheCBProject/ChickenChunks#53]
MC 1.15.2
Forge 31.2.36
Chicken Chunks 1.15.2-2.5.0.77-universal

Unable to break and recover Chunk Loader even with a silk touch pick.

In MC 1.12.2 I was able to pick up a Chunk Loader after placing it.

Has this changed? Should I be able to recover Chunk Loader after breaking it? 

I not seeing anyone else having this issue so it may be another mod...

Thank you for your time,

**Comment by ghost** [comment]
I too am having this issue with both the Chunk Loaders and Spot Loaders.

Minecraft 1.15.2
Forge 31.2.41
Chicken Chunks 1.15.2-2.5.0.77-universal
CodeChicken Lib 1.15.2-3.3.1.379-universal

**Comment by Morpheus1101** [comment]
Confirmed this myself using Forge *.44

**Comment by covers1624** [comment]
Fix has been pushed to curse, awaiting approval.
Please let me know if you experience any more issues.

**Comment by TheOrionsun** [comment]
Thank you for your time in fixing this issue.

I have verified it does work now with the update.

Thank you again!

**Comment by ghost** [comment]
Also confirming the issue is fixed. Thank you!
