### ISSUE TITLE
Link in the readme / on curse leads to 404 error page

### ISSUE THREAD

**Issue by BlackStar7713** [TheCBProject/ChickenChunks#54]
In the readme file it says "Current recommended and latest builds can be found at http://chickenbones.net/Pages/links.html"
That link leads to a 404 error page for me. The same link is on the curse page for unstable builds.

I found the 1.16 version via the maven link, but I figured I'd let you know in case that wasn't intentional.

**Comment by covers1624** [comment]
Closing in favour of meta issue: https://github.com/TheCBProject/ChickenChunks/issues/77
