### ISSUE TITLE
ConcurrentModificationException - Crash at login with 2 chunkloaders placed

### ISSUE THREAD

**Issue by Flexz9** [TheCBProject/ChickenChunks#55]
[crash-2020-09-25_17.43.57-server.txt](https://github.com/TheCBProject/ChickenChunks/files/5288343/crash-2020-09-25_17.43.57-server.txt)
[crash-2020-09-25_17.15.41-server.txt](https://github.com/TheCBProject/ChickenChunks/files/5288344/crash-2020-09-25_17.15.41-server.txt)

Every time I log in I'm having this issue.
Other players don't have chunk loaders yet.

**Comment by covers1624** [comment]
This should be resolved in the latest pending release. Duplicate of: https://github.com/TheCBProject/ChickenChunks/issues/76
