### ISSUE TITLE
[1.10.2] Server crash on stop.

### ISSUE THREAD

**Issue by rmnaderdev** [TheCBProject/ChickenChunks#6]
I keep getting this weird crash when ever I go to shut down my server. I am using sponge but I don't see anything about sponge in the stack trace.

Crash Report: http://pastebin.com/fXcmyPqi

**Comment by covers1624** [comment]
Odd, can you attempt to re create this issue with sponge uninstalled.

**Comment by rmnaderdev** [comment]
I haven't tried to re-create it. Every now and then when I restart the server this happens. It started happening a couple days ago. It's hard to say what's causing it.

**Comment by rmnaderdev** [comment]
I'll see what I can do when I get some time.
