### ISSUE TITLE
Chunk Loading not working unless in dimension

### ISSUE THREAD

**Issue by 792343** [TheCBProject/ChickenChunks#61]
As the problem states chunk loaders aren't working properly unless I'm in the dimension. Try to keep a pump loaded in the nether and it won't work unless I'm in the Nether. Modpack is Valhesia 3, 1.16.4 solo world

**Comment by 792343** [comment]
I should also mention that the pump is mekanism and I'm using ender tanks

**Comment by covers1624** [comment]
Duplicate of: https://github.com/TheCBProject/ChickenChunks/issues/52
