### ISSUE TITLE
ChickenChunks causes server to hangout on startup

### ISSUE THREAD

**Issue by Chielhabils** [TheCBProject/ChickenChunks#62]
I've been using ChickenChunks on my modded server for a week now. 
Last night the server randomly crashed and hasn't worked since. It keeps crashing on startup.
On the Forge forum I got this [answer](https://forums.minecraftforge.net/topic/95724-watchdog-kills-server-because-a-mod-hangs-out/?do=findComment&comment=436581). They told me to report this here.
Here's the crash report: 
[crash-2020-12-29_22.09.28-server.txt](https://github.com/TheCBProject/ChickenChunks/files/5752577/crash-2020-12-29_22.09.28-server.txt).
Can we fix this ourselves or is this due to a bug with ChickenChunks?

**Comment by Psithief** [comment]
Our server (using the same modpack) has the same issue.
I had left the chunkloader on 0 chunks, but I don't know if this is the cause.

(See #51)

**Comment by Kadoba** [comment]
I am also having this issue. At first there wasn't too much of a problem but tried to disable allowOffline in the config but this caused the loaders to not work at all. I then tried to re-enable them but this caused the server to repeatedly deadlock. Now no matter what the setting is, when I log in the server crashes. Please consider adding in a config setting to disable the block for purposes like this.

**Comment by covers1624** [comment]
This should be resolved by changes made in Forge to prevent these deadlocks. See: https://github.com/TheCBProject/ChickenChunks/issues/74
