### ISSUE TITLE
Mekanism and other mod cables and displays disappear or show vertically

### ISSUE THREAD

**Issue by Bidgam** [TheCBProject/ChickenChunks#63]
Upon installing ChickenChunks, Applied Energistics terminal and cables disappear (though their interactive box outline is still there and you can use them), as well as other mod cables. Mekanism mod cables show vertically (see associated image).

Image reference: https://imgur.com/a/8PMN4fP

Minecraft 1.16.4 on Forge 35.1.13

**Comment by covers1624** [comment]
Do you have optifine installed?

**Comment by Bidgam** [comment]
No

**Comment by covers1624** [comment]
Do you have any ChunkLoaders in your player's view? What happens if you remove them?

**Comment by Bidgam** [comment]
No, not that I know of anyway. What's interesting is the Applied
Energistics storage interface started showing properly for a bit there,
then it went back to invisible. I moved away several chunks for a while to
do something else, but I'm not sure if that's the reason. For the most
part, it's always borked.

I'm not sure I mentioned it, but if I destroy a section of the cable, it
fixes itself, until it borks again later on.

**Comment by covers1624** [comment]
If you don't have any chunk loaders placed down, then this is not an issue with ChickenChunks, it has absolutely no effect on how other mods render things.

**Comment by corintho** [comment]
I've seen this happen in a modpack I have, without ChickenChunks. Still trying to point out the culprit, since it is annoying, but I can say for sure ChickenChunks is not.

**Comment by Bidgam** [comment]
I haven't been able to reproduce this as accurately as before for some
reason. We can close this ticket until I can find more on what it's about.
Thanks for helping to investigate.
