### ISSUE TITLE
Chicken chunks causing crash 1.16.4

### ISSUE THREAD

**Issue by Bright7185** [TheCBProject/ChickenChunks#67]
When using chicken chunks my game crashes with this java.lang.ArrayIndexOutOfBoundsException: -1 i dont know how to fix it.

**Comment by covers1624** [comment]
You will need to provide your full crash report. 
This is about as useful as saying your tyre fell off your car and bringing only your tyre to the mechanic.

**Comment by Bright7185** [comment]
[crash-2021-02-18_11.31.04-client.txt](https://github.com/TheCBProject/ChickenChunks/files/6004768/crash-2021-02-18_11.31.04-client.txt)

**Comment by covers1624** [comment]
This crash has nothing to do with chicken chunks. Vanilla is imploding rebuilding lighting for a chunk, nothing i can do.
