### ISSUE TITLE
Server crash at some random point.

### ISSUE THREAD

**Issue by SirEndii** [TheCBProject/ChickenChunks#69]
The Server crashes with the following stacktrace:
https://gist.github.com/Seniorendi/0e35f4dc39f251f083f603eb61435bf3
There is no crash report, the server freezes, and it does not generate one.

I used the restriction command from chickenchunks. If the player I had forbidden with it, the server crashes.

**Comment by covers1624** [comment]
This has been resolved. Duplicate of: https://github.com/TheCBProject/ChickenChunks/issues/76
