### ISSUE TITLE
Chunks not being loaded

### ISSUE THREAD

**Issue by Assaro** [TheCBProject/ChickenChunks#70]
I am running a minecraft server with ChickenChunks-1.16.5-2.8.0.86-universal.jar and for some reason no chunks keep loaded at all. It does not make a difference whether I am on the server or not, also both the chunkloader and the spotloader don't work. I checked the config and everything seems to be right.

**Comment by nobu-sh** [comment]
Same problem except it's only my overworld chunk loaders it appears. I have one in the nether for a lava pump which seems to work fine but the one in my overworld to keep the lava pumping into a tank quits working when I go to the nether to check on the pump site

**Comment by kinvaris** [comment]
Similar problem here, I added the mod in forge 1.16.5.
When nobody is near it or online, it does not work.

**Comment by covers1624** [comment]
This should be resolved in the latest pending release.

**Comment by covers1624** [comment]
Version `2.9.0.87` has now been released which should resolve this issue.
