### ISSUE TITLE
you forgot to tell us how to use

### ISSUE THREAD

**Issue by axelnieves2012** [TheCBProject/ChickenChunks#71]
how to use? should I craft something or what???

**Comment by axelnieves2012** [comment]
I think you should include this info on main description and readme.txt.
I had to get Chunk Loader from creative gamemode.

**Comment by covers1624** [comment]
Replaced with meta issue: https://github.com/TheCBProject/ChickenChunks/issues/77

However, yes, you need to craft a ChunkLoader block.

I recommend installing JEI and searching for ChickenChunks.
