### ISSUE TITLE
Server Crash when placing ChunkLoader

### ISSUE THREAD

**Issue by callmeBartis** [TheCBProject/ChickenChunks#72]
nothing much to say haha, here´s the Crash Log 

[https://pastebin.com/JJUNQQH8](https://pastebin.com/JJUNQQH8)

its version 1.16.5 used the Chickenchunks 1.16.4 universal^^
most mods from 1.16.4 work on 1.16.5 without problems :/

**Comment by covers1624** [comment]
This is an incredibly outdated version of ChickenChunks. Please try with the latest version on curse.
