### ISSUE TITLE
Chunk loader not working...

### ISSUE THREAD

**Issue by Scit00** [TheCBProject/ChickenChunks#75]
I have a minecraft server (with more mods) and i want to keep my iron farm loaded, but when no-one is in the zone the chunk loader just doesn´t work, the floating thing its going up and down and there is not redstone touching it

**Comment by kinvaris** [comment]
Similar problem here, I added the mod in forge 1.16.5. 
When nobody is near it or online, it does not work.

**Comment by covers1624** [comment]
This should be resolved in the next release.

**Comment by covers1624** [comment]
Version `2.9.0.87` has now been released which should resolve this issue.
