### ISSUE TITLE
Lightning strikes / fire on login after nobody online

### ISSUE THREAD

**Issue by ghost** [TheCBProject/ChickenChunks#78]
Version 1.16.5-2.8.0.86

This is perhaps a long shot but this looks a lot like https://bugs.mojang.com/browse/MC-152908, but this was fixed in 1.14.4, and I can't find any reference to the bug for versions that aren't 1.14.1 and 1.14.2.

Again, this could be coincidence, but just yesterday I placed one of your chunkloaders on my server and when I logged in half a day later, I experienced exactly what is described in the Mojang issue.

Just wondering if perhaps your mod could have reintroduced this bug / if you could just verify that it isn't your mod.

I will be removing the chunkloader from my world for the time being to see if this happens again without it, so that I can confirm this to myself.

(It's a bit scary as the rain has obviously already stopped, resulting in mass amounts of fire from the lightning strikes).

Thanks!

**Comment by covers1624** [comment]
This is not a bug. You will find that it did not 'replay all the events that would have happened', as per the original Mojang report.

ChickenChunks loads chunks, these chunks tick, have weather, crops grow, machines work, it acts as if there is _actually_ a player in its radius.

This is intended behavior.

**Comment by ghost** [comment]
Perhaps I did not explain properly. I understand that this is the purpose of a chunk loader (of course, that's why I wanted it). My issue was that the lightning seems to wait for someone to login and then all go off at once.
As the weather by that point has already changed, there is nothing to extinguish the fires.

**Comment by ghost** [comment]
Considering that this is a bug that is supposed to be fixed already on Mojang's side, the nature of your mod, and the fact that it only happened when I had a chunkloader active, I figured that there's a decent chance it could be something on the mod's end.

**Comment by covers1624** [comment]
I will re-open this for further investigation.

**Comment by covers1624** [comment]
After much troubleshooting. I was unable to reproduce this in any capacity, chunks that are loaded by a ChunkLoader do not 'buffer' their lightning events until the player logs in, these events were played immediately, resulting in fire spreading in chunks loaded by ChickenChunks. There exists no mechanism in Minecraft for these events to be 'buffered'.

If this issue persists it is likely the result of another mod.
