### ISSUE TITLE
Unable to change size of chunks being loaded

### ISSUE THREAD

**Issue by snoopydude48** [TheCBProject/ChickenChunks#79]
Using ChickenChunks-1.16.5-2.9.0.87-universal.jar.  Tried with a personal mod pack and just this mod.  Place a chunk loader and click the + / - buttons to change the size of the loaded chunks.  The numbers don't change and the actual chunk loading size does not change.

**Comment by JustACoolDude** [comment]
Same here; additionally, it seems like you can't change the shape of the lasers either (it's stuck on square).

**Comment by DreadsCasey** [comment]
I have this same issue. Running Minecraft version 1.16.5 forge 36.2.9 on Ubuntu 20.04.

**Comment by brandon3055** [comment]
This issue has now been resolved.
