### ISSUE TITLE
Per-group chunk limiting?

### ISSUE THREAD

**Issue by EmanYm** [TheCBProject/ChickenChunks#8]
In the config is a per-player chunk limit.  I am wondering if I need to add each player's name here, or if I can add limits per permission group.

Also, I'm not sure if the number "12,500" is a typo.
>#Forge gives everyone 12500 by default

**Comment by covers1624** [comment]
Hmm, don't really know a good way to pull this off. Open a new issue at https://github.com/TheCBProject/Feedback
