### ISSUE TITLE
Server crashes on startup, seems to hang as server tick is over 180 seconds.

### ISSUE THREAD

**Issue by ghost** [TheCBProject/ChickenChunks#80]
When starting the server it seems the server hangs when trying to load chunks, I am using Chicken Chunk version 2.9.0.87 and forge version 36.2.8 (latest).

It was working fine unto we upgraded to 2.9.0.87 and now ever downgrading back to 86 does the same thing. See crash logs attached.

[crash-2021-11-04_01.21.15-server.txt](https://github.com/TheCBProject/ChickenChunks/files/7472529/crash-2021-11-04_01.21.15-server.txt)

[crash-2021-11-04_01.15.36-server.txt](https://github.com/TheCBProject/ChickenChunks/files/7472530/crash-2021-11-04_01.15.36-server.txt)

Would be grateful for any help.

**Comment by planetguy32** [comment]
Also seeing this on my server. The crash report looks [largely the same](https://pastebin.com/ccRb2C3s) to me.

In case it's of interest, we built a few loaders next to each other - [screenshot](https://media.discordapp.net/attachments/906321164371116114/913161274429440038/unknown.png?width=960&height=448). If it would help, I can upload the world save and server files - [here's](https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond/files/3514608) the compatible modpack.

**Comment by covers1624** [comment]
This should be resolved with version [`2.9.1.89`](https://www.curseforge.com/minecraft/mc-mods/chicken-chunks-1-8/files/3596096).

If the issue persists, please reply to the issue.
