### ISSUE TITLE
Nobody on Server Chunk Loader Stop working

### ISSUE THREAD

**Issue by ZeroTronix** [TheCBProject/ChickenChunks#81]
Hey i host my Own server with the modpack [Intelligence: New Horizon](https://www.curseforge.com/minecraft/modpacks/project-413512) and when nobody is on the Server the Chunk loader stop working. I put 2 mods extra in the Modpack [Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity) and [Performant](https://www.curseforge.com/minecraft/mc-mods/performant) could it be that on from the mods kill the chunk loader?

**Comment by covers1624** [comment]
I recommend double-checking that ChickenChunks's `allowOffline` config value is set to `true`, otherwise this sounds like another mod messing with chunk loading.
