### ISSUE TITLE
Dead link: https://chickenbones.net/Pages/links.html

### ISSUE THREAD

**Issue by NotFitForPurpose** [TheCBProject/ChickenChunks#82]
This needs to be fixed on this page:
  https://github.com/TheCBProject/ChickenChunks

and in the Minecraft "Mods" screen "Website" button.
The "Website" button should link to:
  https://www.curseforge.com/minecraft/mc-mods/chickenchunks

Minecraft tile screen
> Mods button
 > "mods with updates" tick-box
  > Chickenchunks
   > Website button

**Comment by covers1624** [comment]
These issues have been resolved.
