### ISSUE TITLE
Incompatibility with Galacticraft

### ISSUE THREAD

**Issue by wdh7987** [TheCBProject/ChickenChunks#83]
The dimensions that are added from Galacticraft and the official expansion mod Extra Planets are not kept loaded by the chunk loader. I have chunk loaders on Kepler 22b, my Eris space station, and on the overworld, and I have to go through loading screens to access each one. Without the chunk loaders, if I went from, say, the overworld to the space station and back quickly no loading screen was needed at all.

**Comment by surfishs** [comment]
hi，how to open the chunk loaders？

**Comment by covers1624** [comment]
Which Minecraft version and Mod version is this?

Can you please try reproducing this on the latest(2.9.1.89) version of ChickenChunks? 

ChickenChunks does no special logic to 'keep dimensions loaded', it simply registers a ticket with Forge.
