### ISSUE TITLE
I can't use the command to view the list

### ISSUE THREAD

**Issue by surfishs** [TheCBProject/ChickenChunks#85]
/chunkloaders
Can you tell me why my friend and I have the same problem

**Comment by pat-gal** [comment]
Same problem for me on 1.16.5 with latest version of ChickenChunks 1.16.5-2.9.0.88-universal. Command is not available on both multiplayer and singleplayer. Does this command still exist on 1.16?

**Comment by covers1624** [comment]
The `/chunkloaders` command was removed in the 1.15 update due to the Forge API's required being removed.

A replacement for this in the future is being considered, however, will likely be _very_ different.
