### ISSUE TITLE
Game Crash 1.19.2 + OptiFine

### ISSUE THREAD

**Issue by calliopemg** [TheCBProject/ChickenChunks#89]
Minecraft: 1.19.2
Forge: 43.1.3
Java: 17.0.3 (OpenJDK)

OptiFine: 1.19.2_HD_U_H9

Error: `java.lang.IllegalStateException: Pose stack not empty`

Originally noticed this with shaders enabled, but then created a new debug pack with only OptiFine and ChickenChunks installed and it still happens with default OF settings and no shaders enabled. Might not actually have to do with OptiFine, but OptiFine is in the stacktrace so that's my best guess. 

Steps to reproduce: 
- I can provide a curseforge pack if needed
- /give <player> chickenchunks:chunk_loader
- Change to inventory slot that has the chunk loader in it
- Game immediately crashes when chunk loader is in the player's hand
- I got past this point once, then the game crashed when I pressed `q` to drop the chunk_loader. 
- When I got past the error briefly, I was able to place the object into the world and interact with it without issue. 

I'm happy to help test if there's any more info you need. 

Full Crash Report: [crash-2022-08-29_01.36.39-client.txt](https://github.com/TheCBProject/ChickenChunks/files/9441857/crash-2022-08-29_01.36.39-client.txt)

**Comment by calliopemg** [comment]
This may actually be a problem with the CodeChickenLib mod? Just got the same crash with EnderStorage ender chest which uses that mod as well.

**Comment by covers1624** [comment]
ChickenChunks, EnderStorage and CodeChickenLib do not even remotely touch the code where this is breaking.

Optifine is not supported.

I recommend you report this issue to them as it is highly likely to occur without any mods present.

**Comment by calliopemg** [comment]
@covers1624  I removed optifine and the mod causes a crash in the "LevelRenderer" This is now an instance with nothing but codechickenlib and chickenchunks loaded. Here's the new crash report if you're interested. It really seems like this is a codechickenlib bug to me, but I don't have experience with mod development so if I'm wrong I'd love to learn why.

[crash-2022-08-31_21.31.18-client.txt](https://github.com/TheCBProject/ChickenChunks/files/9466135/crash-2022-08-31_21.31.18-client.txt)

**Comment by covers1624** [comment]
Appologies, this was caused by CCL.

This should be resolved by updating CCL to [this version](https://maven.covers1624.net/codechicken/CodeChickenLib/1.19.2-4.3.0.470/CodeChickenLib-1.19.2-4.3.0.470-universal.jar). CurseForge approval pending.

**Comment by calliopemg** [comment]
Thanks that definitely fixed it!
