### ISSUE TITLE
Crash on start due to config?

### ISSUE THREAD

**Issue by Natey214** [TheCBProject/ChickenChunks#9]
Hello, my friend has been having some trouble starting his games with me. While my minecraft loads fine, his with all of the exact mods and config crashes on start. Here is a copy of the crash report. 

http://pastebin.com/2DahxTee

Minecraft:1.10.2
Forge: 12.18.3.2221
Chunks: 1.10.2-2.2.0.52-universal

**Comment by covers1624** [comment]
Something is locking the file. Close any programs that could be using the file, all else fails reboot.
