### ISSUE TITLE
Failure to load in 1.19.2/Forge 43.1.3

### ISSUE THREAD

**Issue by UnixRonin** [TheCBProject/ChickenChunks#91]
I'm getting a 'Mod failed to load properly' error in 1.19.2/43.1.3 in both ChickenChunks and EnderStorage, with ChickenChunks-1.19.2-2.9.4.97, CodeChickenLib-1.19.2-4.3.0.470, EnderStorage-1.19.2-2.10.1.181.  Is this a known issue?

**Comment by covers1624** [comment]
Please provide your full logs.

This is like asking your mechanic to fix your car and leaving it at home :)

**Comment by UnixRonin** [comment]
Well, yeah, figured I'd ask if there was a known issue first.  :)

I'll do some diagnostics later today and pull a log.

**Comment by UnixRonin** [comment]
I've determined there is a mod conflict involved, working on narrowing it down now.

**Comment by UnixRonin** [comment]
OK, with only those three mods loaded everything is fine, which establishes it definitively as a mod conflict.  I was **NOT** able to identify **which** mod is conflicting, or reproduce the failure in order to capture a crash log, because while trying to narrow it down I was running into what seemed like maybe persistent memory leakage issues that were making it almost impossible to complete worldgen, which in turn was making it extremely difficult to narrow down which mod(s) were causing the problem.  But whatever it is, the problem does not appear to be in your code.
