### ISSUE TITLE
setblock help

### ISSUE THREAD

**Issue by jagprog5** [TheCBProject/ChickenChunks#98]
Minecraft version 1.12.2

How would I go about using `/setblock` to set a spotloader at a position. Can't quite figure out the datatags.

I'm tried variants like:

```txt
/setblock 100008 8 100006 chickenchunks:chunk_loader 0 replace {radius:"1"}
```

However this causes the block to be stuck with a radius of 0.

My goals are:
 - placing a spot loader
 - owned by player who called the command

Thanks.

edit:

ended up being like: `/setblock 100008 8 100006 chickenchunks:chunk_loader 1 replace {owner: "name_here"}`

however the loader doesn't activate until after the chunk is reloaded from disk...

**Comment by covers1624** [comment]
This is an interesting use case. I'm not sure how to handle this at the moment tbh.

It's possible for some admin commands to be added in the future to load and set a chunk loader at a specific spot.

I'll leave this open.

**Comment by jagprog5** [comment]
Related request: make it so a chunk loader can be owned by the server, and not any particular player. This would function like it was owned by an op account, but without the need to have an opped player. This can be implemented by reserving a special string value for the owner (one which can never be a valid username).

The use case is to have a "command chunk", a chunk super far away which has command blocks, which should always be loaded. Ideally this chunk can be entirely generated by commands (including the placement of the spotloader, hence this issue, and the need to have it be owned by the server).
